services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: vmmanager
      POSTGRES_USER: vmuser
      POSTGRES_PASSWORD: vmpass
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
